# Generated by Django 4.1.6 on 2023-04-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(choices=[("Pinjaman", "Tagihan")], max_length=20),
                ),
                ("amount", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField()),
                ("description", models.TextField()),
            ],
        ),
    ]
