# Generated by Django 4.2 on 2023-04-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField(default=0)),
                ('annual_interest', models.IntegerField(default=0)),
                ('tenor', models.IntegerField(default=0)),
                ('monthly_payment', models.FloatField()),
                ('accumulated_payment', models.FloatField()),
            ],
        ),
    ]
